### ISSUE TITLE
EthDCRMiner64 not found

### ISSUE THREAD

**Issue by shingle01** [Swaggadan/Zilliqa-Switcher#1]
Under the v0.5.5 code I have seen occasions where zil switcher fails to detect EthDCRMiner64.exe.  Will say EthDCRMiner64 not found and lock up.  Meanwhile EthDCRMiner64.exe is running and mining as per usual.  I suspect there may be a timing issue, perhaps a longer wait time or retry timeout option is required?

**Comment by da-tai** [comment]
Try using updated version
